[package]
name = "rust-solutions"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.3"
num = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
